image: python

stages:
  - test
  - build
  - deploy

check:
  stage: test
  before_script:
    - pip3 install 'black>=23,<24' 'ruff==0.0.239'
  script:
    - pip3 install --editable .
    - black --check --diff --color .
    - ruff src/mhm_tools

test:
  stage: test
  script:
    - pip3 install --editable .[test]
    - python -m pytest --cov mhm_tools --cov-report term-missing --cov-report html:cov --cov-report xml:cov.xml -v tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
    paths:
      - cov

documentation:
  stage: build
  script:
    - pip3 install --editable .[doc]
    - sphinx-build docs/source docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0  # to have all tags
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - documentation
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - main
